# Documentation for all configuration options:
# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "bundler"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ruby"
    cooldown:
      default-days: 7
    groups:
      bundler:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github_actions"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
